### ISSUE TITLE
"Attributed by the system" is not supported by Wikibase

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#10]
The [DMG](https://github.com/weso/SAF-Lux/blob/main/import_scripts/property_builder/DM_SAF_vers.1.0.1.xlsx)  currently has a few fields that are assigned as to be "Attributed by the system", however Wikibase currently does not support automatic population of properties. User and version history is captured as metadata in Wikibase, but this is in a separate database that is not part of the linked data part, but more to the core mediawiki engine. 
It should be technically feasible to transpose this to the SAF, but is a project of its own.

**Comment by andrawaag** [comment]
There is the exception for  "date of creation" and " date of modification". However these are part of the standard metadata of a Wikibase item and not visible in the user facing interface

**Comment by mzeinstra** [comment]
Than this will be done by robot, made by 1024. Which properties are these?

**Comment by mzeinstra** [comment]
After discussion this issue is not high priority at the moment. It will be dealt with after an initial implementation

**Comment by mzeinstra** [comment]
Closing this issue until WP5 opens a specific one.
