### ISSUE TITLE
Example data contains mixed data types.

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#14]
The example data has values within one field with mixed datatypes. This sometime creates issue while parsing the code to be serialized in Wikibase. For example the field "Alternative / other form(s) of name:Type", contains value of type "None", string and int. 
These values represent the direct versus the indirect form of the data, and need to be split. The split function chokes on int values. A temporary fix is to cast all int values to string. 

e.g. Wiesen, Michel

**Comment by joelthill** [comment]
Excel will allow me to force INT to STRING by prefixing the number with a ', but in the absence of data, it will very likely remain NONE. Putting just a quote may be a workaround, but then again, it might be easier to cast it systematically in your script ?

**Comment by mzeinstra** [comment]
Does this need to be resolved in the test dataset? I'll leave it up to you two to resolve this.

**Comment by andrawaag** [comment]
In the test script this was already fixed. This issue was more for future reference. So will close
