### ISSUE TITLE
Multilinguality in the import data

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#15]
Multilinguality in the import data is currently treated as alternative names. e.g. 
"de Lutzemburgo', 'von Luxemburg', 'de Lutzenburgo'" 
Wikibase however supports language tags. A parser for the import data requires explicit language tags to be able to assign those in WIkibase. In future structures of the multilingual names and titles, a different hierarchy is needed that includes explicit language tags for the alternative (and possibly main)  names

**Comment by mzeinstra** [comment]
This will most likely resolve itself when data from the institutions use the ShEx of the CIDOC ontology to structure and format their data.

**Comment by mzeinstra** [comment]
Has links to #25
