### ISSUE TITLE
Create an RDF/XML file example following the CIDOC/CRM model

### ISSUE THREAD

**Issue by labra** [weso/SAF-Lux#2]
Add an RDF/XML file containing an example that follows the CIDOC/CRM model

**Comment by joelthill** [comment]
thanx José!
j.

**Comment by mzeinstra** [comment]
For the documentation this is about https://github.com/weso/SAF-Lux/blob/main/examples/examplesFromSAF.xml or this commit: https://github.com/weso/SAF-Lux/commit/9293944f448a2b988aa9ec775a665dd55ec6f963
