### ISSUE TITLE
Replace string based rdfs:labels in CIDOC_CRM representation by proper nodes

### ISSUE THREAD

**Issue by labra** [weso/SAF-Lux#22]
In the previous representation we were using the rdfs:label property to represent the labels in the PDF diagram using xsd:string literal values.

For example:

```turtle
:philipName rdf:type crm:E90_Symbolic_Object ;
   rdfs:label "name"@en, "nom"@fr ;
   crm:P2_has_type afl:direct ;
   afl:value "Philip" .
```

One problem of literal values in RDF is that they are terminal and it is not possible to further annotate them, so if we want to attach multilingual labels, we have to associate them directly to the name node which is redundant and error-prone.

An alternative approach, is to use an IRI node like `afl:name` which can later have multilingual labels associated. In that way, the previous example could be:

```
:philipName rdf:type crm:E90_Symbolic_Object ;
   afl:label afl:name ;
   crm:P2_has_type afl:direct ;
   afl:value "Philip" .

afl:name rdfs:label "name"@en, "nom"@fr .
```

In this way, the `afl:name` node can be reused by all names and its corresponding multilingual labels only need to be declared once.

**Comment by mzeinstra** [comment]
Who needs to resolve this issue? Is this something for Michelle to decide on, or is this a design choice that you can make yourself?

**Comment by labra** [comment]
I took the decision by now in the ShEx file but I wanted to let you know about it and it may be good if someone else could give the go-ahead.
