### ISSUE TITLE
birth and death dates not loaded

### ISSUE THREAD

**Issue by joelthill** [weso/SAF-Lux#26]
is this related to the EDTF plugin not yet installed?

**Comment by digitaalwerktuig** [comment]
@andrawaag Can you answer this question?

**Comment by andrawaag** [comment]
On WBStack the EDTF plugin is installed. However, EDTF, being a new plugin, is not yet (completely) supported by the import libraries. So it is possible to add EDTF dates manually, but not yet programmatically. Except maybe by writing a direct wrapper around the API.
