### ISSUE TITLE
Person needs to be part of a closed list

### ISSUE THREAD

**Issue by mzeinstra** [weso/SAF-Lux#29]
We need to be able to set an item to "is instance of" "person" 

Person is not part of a closed list yet.

**Comment by mzeinstra** [comment]
To be more specific. https://lux-saf-beta.wiki.opencura.com/wiki/Item:Q78 is not automatically created on https://saf-dev.bnl.lu/

**Comment by andrawaag** [comment]
This is correct,  the CIDOC-CRM part of the scripts did not run on the https://saf-dev.bnl.lu/ instance, so none of the CIDOC-CRM terms are loaded there yet. The script did run on WBStack, hence its appearance there. 

Adding it manually for now is indeed a good solution, until we settled on a CIDOC-CRM version.

**Comment by andrawaag** [comment]
I have added the scripts used to instantiate the staging server to the Github repository. I also added a snippet to this python script to instantiate the person item.
