### ISSUE TITLE
Maintain a grouping of the properties in Wikibase

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#3]
In the DMG sheet where mapping between the CIDOCCRM and Wikibase properties are being maintained there is a grouping of the different properties. It is important to maintain that order as it is depicted in the DMG sheet. Implicitly this can be achieved by creating the properties in the required order, but it might be saver to make that order explicit. This is similar to Wikidata where P31 en P279 (instance of and subclass of) are being grouped.

**Comment by mzeinstra** [comment]
Can we operationalise this? Who is assigned to this ticket. What is the process to do in order to close this issue?

**Comment by andrawaag** [comment]
Maybe @JeroenDeDauw? 

What is needed to close is a description on how to cluster properties differently to the default numerical sequence. This is for example similar to the properties P31 and P279 in Wikidata always be first. How can this be replicated in Wikibase and to what detail? (e.g. how many subgroups)

**Comment by JeroenDeDauw** [comment]
As far as I know there is no way to order statements by property in the UI, beyond using this grouping feature. I'd be very surprised if the order can be saved on a data model or on a per-item level.

As to the grouping feature: I am not familiar with it and would need to ask on the Wikibase community chat how to use it.

**Comment by andrawaag** [comment]
What is this grouping feature you refer to and how detailed is it?

**Comment by JeroenDeDauw** [comment]
I was referring to what you wrote, so you tell me. I don't know.

> Wikidata where P31 en P279 (instance of and subclass of) are being grouped.

**Comment by JeroenDeDauw** [comment]
I can confirm that you cannot add references for a qualifier. I also can't think of further options that would be better than the ones listed. In SMW you could use "subobjects" but there is no equivalent in Wikibase (beyond creating multiple dedicated items).

How to best represent the data within the limits of the Wikibase software is really a data modelling question, not my area of expertise. You could try asking on the Wikibase mailing list or telegram, but I'd be surprised if there is a nice way of achieving what you want.

**Comment by andrawaag** [comment]
No, it is a different - simpler - issue. If you go to any Wikidata item, P31 (instance of) and/or P279 (subclass of) is always on top, although properties with lower numbers follow afterwards. By default, the numbers are following each other (1 follows 2, follows 3) etc. So there is a mechanism in place that allows a different order. I would like to know where in Wikibase P31 and P279 are configured to be always on top.  

I will seek advise in the wikibase channel.

**Comment by andrawaag** [comment]
The Wikibase community was quick :)
The feature is called SortedProperties and documented [here](https://www.mediawiki.org/wiki/Manual:Interface/Wikibase-SortedProperties).
