### ISSUE TITLE
Statements can be created using their labels

### ISSUE THREAD

**Issue by digitaalwerktuig** [weso/SAF-Lux#30]
On the staging instance of Wikibase at the National Library (we still need to check if it's the same for WBstack), statements can be created using their lables, but only the property and qualifiers numbers.

**Comment by digitaalwerktuig** [comment]
Confirmed it works on WBstack.

**Comment by mzeinstra** [comment]
This works:
<img width="924" alt="Screenshot 2021-07-15 at 10 42 33" src="https://user-images.githubusercontent.com/5627431/125764215-fa494ffd-8998-4086-b706-bc951b9d9523.png">
this does not work:
<img width="934" alt="Screenshot 2021-07-15 at 11 24 46" src="https://user-images.githubusercontent.com/5627431/125764344-84b038d2-cde6-4a96-8a49-047e837a70e8.png">

**Comment by mzeinstra** [comment]
This has been fixed.
