### ISSUE TITLE
Ways to deduplicate exact duplicate statements

### ISSUE THREAD

**Issue by mzeinstra** [weso/SAF-Lux#31]
I did a test on merging two records and even exact statements were merged. I expected that these were automatically deduplicated. 

<img width="929" alt="Screenshot 2021-07-16 at 16 27 15" src="https://user-images.githubusercontent.com/5627431/125963369-11b40a37-ccd9-48f7-b5a6-e76730ac255b.png">

How does deduplication of exact statements work?

(this might not be a good issue for this repo)

**Comment by andrawaag** [comment]
Can you share an example item? Given the values are identical, this should not occur.

**Comment by mzeinstra** [comment]
Can't reproduce this on lux-saf-beta, it did happen on saf-dev.bnl.lu

**Comment by mzeinstra** [comment]
I could also not replicate this anymore on a the SAF-DEV server. closing..
