### ISSUE TITLE
Create a SAF-Lux vocabulary

### ISSUE THREAD

**Issue by labra** [weso/SAF-Lux#35]
Following [linked data best practices]() It is a good practice in Semantic Web to define the properties and classes employed whose definition could be dereferenciable from the namespace. 

As an example, the [ShEx schema](https://github.com/weso/SAF-Lux/blob/main/shex/rules_1.0.1.shex) is using some properties like `afl:value` or `afl:label` which could be defined at least in some RDF Schema as:

```
prefix afl:  <http://data.culture.lu/ns>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

afl:value a rdf:Property ;
  rdfs:label "Value"@en .
```

There are other properties that are used in the ShEx Schema which belong to the CIDOC-CRM or the FRBROO conceptual models which we should decide how to represent. For example, `E21_Person`. We have 3 possibilities:

a.- Create a proxy property/class in Lux namespace. Something like: `http://data.culture.lu/ns/E21_Person` and map that new property to a property from CIDOC_CRM. There is a linked data version of CIDOC-CRM located at: http://erlangen-crm.org/current/ but it seems to be using an old version of CIDOC-CRM.
b.- Create a proxy property/class as in previous step but map it to the current/official namespace of CIDOC-CRM. Is it `http://www.cidoc-crm.org/cidoc-crm` ?
c.- If the official namespace for CIDOC-CRM is indeed `http://www.cidoc-crm.org/cidoc-crm`, we may just use those properties directly without creating a local proxy.
d.- We could create a mirror of CIDOC CRM in a local wikibase maintained by Lux. This option has already been discarded, but I added it for documentation purposes.

If we opt for options b. or c. we need to check the namespace for frbroo. I think it is: `http://iflastandards.info/ns/fr/frbr/frbroo/`. 

At this moment I am inclined by option c) using the namespaces `http://www.cidoc-crm.org/cidoc-crm/` for crm and `http://iflastandards.info/ns/fr/frbr/frbroo/` but I would like to confirm if those are the official namespaces before taking a final decision.

**Comment by labra** [comment]
Trying to guess if `http://www.cidoc-crm.org/cidoc-crm` is the reference URI for CIDOC I tried to do:

```
λ curl -H "Accept: text/turtle" -I http://www.cidoc-crm.org/cidoc-crm/
HTTP/1.1 303 See Other
Date: Mon, 02 Aug 2021 14:45:12 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: http://www.cidoc-crm.org/html/5.0.4/cidoc-crm.html
Content-Type: text/html; charset=iso-8859-1
```

and it redirects to version 5.0.4 which is outdated. The latest version at this moment is: 7.1.1 (see: http://www.cidoc-crm.org/versions-of-the-cidoc-crm).

I noticed that there is a machine readable specification in XML at: http://cidoc-crm.org/versions/cidoc_crm_v7.1.1.xml which is tranalated to HTML using this [XSLT](https://cidoc-crm.org/versions/CidocXml2HTML.xslt). The XML specification doesn't define a namespace.

On the other hand, in the case of FRBROO it seems that the vocabulary is indeed available at: `http://iflastandards.info/ns/fr/frbr/frbroo/` and after running: 

```turtle
λ curl -H "Accept: text/turtle" http://iflastandards.info/ns/fr/frbr/frbroo/
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix reg: <http://metadataregistry.org/uri/profile/regap/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<http://iflastandards.info/ns/fr/frbr/frbroo/>
    dc:title "FRBRoo model"@en ;
    skos:note "Element set of the Functional Requirements for Bibliographic Records object-oriented extension to the the CIDOC Conceptual Reference Model (CRM)"@en .

<http://iflastandards.info/ns/fr/frbr/frbroo/CLP104>
    reg:name "subjectTo"@en ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a rdf:Property ;
    rdfs:comment "This property associates a publication, i.e. an instance of F3 Manifestation Product Type, with an instance of E30 Right, which applies to all exemplars of that publication, as long as they are recognised as exemplars of that publication. The rights covered by this property may include: acquisition or access authorisation; terms of availability; access restrictions on the Manifestation Product Type; etc."@en ;
    rdfs:domain <http://iflastandards.info/ns/fr/frbr/frbroo/F3> ;
    rdfs:isDefinedBy <http://iflastandards.info/ns/fr/frbr/frbroo/> ;
    rdfs:label "subject to"@en ;
    rdfs:range <http://www.cidoc-crm.org/cidoc-crm/E30_Right> ;
    owl:inverseOf <http://iflastandards.info/ns/fr/frbr/frbroo/CLP104i> ;
    owl:sameAs <http://iflastandards.info/ns/fr/frbr/frbroo/CLP104_subject_to> ;
    skos:definition "This property associates a publication, i.e. an instance of F3 Manifestation Product Type, with an instance of E30 Right, which applies to all exemplars of that publication, as long as they are recognised as exemplars of that publication."@en ;
    skos:scopeNote "The rights covered by this property may include: acquisition or access authorisation; terms of availability; access restrictions on the Manifestation Product Type; etc."@en .
. . .

```

**Comment by mzeinstra** [comment]
The comments of show that this a really recent document:

`
CIDOC CRM v7.1.1 encoded in XML
--
  |  
  | This is the encoding approved by CRM-SIG in the meeting {{pending for approval}}.
  |  
  | Note that this is NOT a definition of the CIDOC CRM, but an encoding
  | derived from the authoritative release of the CIDOC CRM v7.1.1 May 2021 on
  | http://cidoc-crm.org/Version/version-7.1.1
  |  
  | The following XML elements define their innerText in HTML format:
  | - examples
  | - inFirstOrderLogic
  | - propertyOfProperty
  | - quantification
  | - scopeNote
  |  
  | Created by FORTH-ICS Sunday August 01, 2021
`

What will be de consequence of this document for your work?

**Comment by labra** [comment]
Once we identify the right namespace for CIDOC-CRM and FRBROO properties, the only consequence is that we should use those namespaces in the different documents and RDF encodings. As an example, I already changed that in the new version of the ShEx document here: https://github.com/weso/SAF-Lux/blob/main/shex/rules_1.0.2.shex

I added a CHANGE LOG comment at the beginning to keep track of the different changes to that ShEx file.

I expect to generate an RDFS vocabulary derived from that ShEx file soon so we can close this issue.

**Comment by labra** [comment]
I have created a first version of the vocabulary that is automatically converted from the ShEx file using the code that is available at [shex2rdfs folder](https://github.com/weso/SAF-Lux/tree/main/shex2rdfs).

The rdfs file is available at [website/saf-vocabulary.ttl](https://github.com/weso/SAF-Lux/blob/main/website/saf-vocabulary.ttl)

I will close this issue by now and open further issues about improving both the RDFS generated or the script that generates it.
