### ISSUE TITLE
Change literals to URI in SheX file

### ISSUE THREAD

**Issue by mzeinstra** [weso/SAF-Lux#39]
Hi @kwisatz @labra @joelthill

Yesterday José asked if there were no objections to changing the literals in the closed lists of the SheX files into URI. 

This has upstream effect in the ingestion pipeline that David and Joel are working on.

I spoke to Joel to see if this would provide any problems in his conversion tools, he said that he could easily change his logic to reflect this.

@kwisatz would you have issues with having these closes lists as URIs?  If not, @labra can make the changes.

Example of a change. On line 119 of https://github.com/weso/SAF-Lux/blob/main/shex/rules_1.0.2.shex the four gender possibilitie are literals. The proposition is to make these literals in to URIs.

**Comment by kwisatz** [comment]
No, I don't think that this would have an impact on my work.

**Comment by joelthill** [comment]
makes total sense

**Comment by mzeinstra** [comment]
@labra please go ahead and make those changes to the ShEx.

**Comment by labra** [comment]
I have done the pull request and merged it.

**Comment by kwisatz** [comment]
@labra just letting you know what a shex file with version 1.0.3 has not yet been pushed to https://github.com/weso/SAF-Lux/tree/main/shex

**Comment by labra** [comment]
Ops, you were right, I have created again the pull-request and now I think it is right.
