### ISSUE TITLE
Adding the version of the applicable CIDOC-CRM as metadata to the DMG.xls file

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#5]
The [DMG](https://github.com/weso/SAF-Lux/blob/main/import_scripts/property_builder/DM_SAF_vers.1.0.1.xlsx) captures the mappings between CIDOC-CRM and the SAF Wikibase in Luxembourg. 

Can we add the applicable version of CIDOC-CRM to the excel file.

**Comment by mzeinstra** [comment]
Please do so @andrawaag

**Comment by mzeinstra** [comment]
This has been discussed the CIDOC CRM version will be placed on top of the DMG file

**Comment by michellePfeiffer** [comment]
For the current version of the data model (xls file)  reference has been made to  version 7.1.1. of CIDOC CRM
