### ISSUE TITLE
separating the different note types in distinct properties

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#6]
Currently the model in [DMG](https://github.com/weso/SAF-Lux/blob/main/import_scripts/property_builder/DM_SAF_vers.1.0.1.xlsx) contains a field about note, where in CL2 the types are defined. I would propose to separate those in distinct properties in Wikibase. ie. internal note and public note.

**Comment by mzeinstra** [comment]
I agree, please do this in your example implementation

**Comment by mzeinstra** [comment]
See #9 it is agreed to make this into separate properties as long as they can be mapped back to v1.1.0 structure 

@andrawaag will implement this in the the ingestion script
