### ISSUE TITLE
Which date data types to use?

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#7]
Currently both the time and edtf datetypes are supported in Wikibase. Do we stick to EDTF for all timestamps, or are there cases where EDTF is not needed (e.g. system time stamps)

**Comment by mzeinstra** [comment]
We will only use EDTF when the possible expression calls for it. So not for system time stamps

**Comment by mzeinstra** [comment]
My comment was confirmed during the meeting

in V1.2.0 @andrawaag will introduce "EDTF" as a separate datatype.
