### ISSUE TITLE
Entering the superclass and subclass of source type directly to Wikibase

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#8]
Currently [DMG](https://github.com/weso/SAF-Lux/blob/main/import_scripts/property_builder/DM_SAF_vers.1.0.1.xlsx)  lists a hierarchy for source of information. I would recommend removing this from DMG (or add it to a separate sheet).

**Comment by mzeinstra** [comment]
Can you make a proposal DMG document where you do this?

**Comment by mzeinstra** [comment]
This is part of the OWL model, it can be removed from the DMG.

**Comment by mzeinstra** [comment]
@andrawaag you can remove this from your 1.2.0 version
