### ISSUE TITLE
Move CL7 to distinct properties in Wikibase

### ISSUE THREAD

**Issue by andrawaag** [weso/SAF-Lux#9]
The current model in [DMG](https://github.com/weso/SAF-Lux/blob/main/import_scripts/property_builder/DM_SAF_vers.1.0.1.xlsx)  contains a controlled list of identifier scheme's, but I propose to move those identifiers to direct external id properties

**Comment by mzeinstra** [comment]
I agree with this. Each external identifier should be its own property

**Comment by mzeinstra** [comment]
During discussion with WP3 it was agreed that this is ok to do, as long as this can be mapped back to the CIDOC-CRM model.
